import React, { createContext, useState, useContext, ReactNode, useCallback, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'zh' | 'ur';

const translations: Record<Language, Record<string, string>> = {
    en: {
        'app_title': 'Attendance System',
        'sign_in_continue': 'Please sign in to continue',
        'username': 'Username',
        'password': 'Password',
        'sign_in': 'Sign In',
        'signing_in': 'Signing In...',
        'quick_login_as': 'Quick Login As:',
        'employee': 'Employee',
        'manager': 'Manager',
        'admin': 'Admin',
        'logout': 'Logout',
        'role_employee': 'Employee',
        'role_manager': 'Manager',
        'role_admin': 'Admin',
        'remember_me': 'Remember Me',
        'syncing': 'Syncing...',
        'synced_at': 'Synced at {time}',
        'sync_error': 'Sync Error',
        'date': 'Date',
        'status': 'Status',
        'reason': 'Reason',
        'actions': 'Actions',
        'edit': 'Edit',
        'cancel': 'Cancel',
        'approve': 'Approve',
        'reject': 'Reject',
        'name': 'Name',
        'location': 'Location',
        'attendance_action': 'Attendance Action',
        'todays_status': "Today's Status",
        'leave_management': 'Leave Management',
        'monthly_attendance_summary': 'Monthly Attendance Summary',
        'attendance_history': 'Attendance History',
        'leave_request_history': 'Leave Request History',
        'checked_in': 'Checked In',
        'checked_out': 'Checked Out',
        'not_checked_in': 'Not Checked In',
        'check_in_time': 'Check-In Time',
        'check_out_time': 'Check-Out Time',
        'check_in_with_selfie': 'Check In with Selfie',
        'check_out_with_selfie': 'Check Out with Selfie',
        'attendance_complete_today': 'Your attendance for today is complete.',
        'leave_request_prompt': 'Need to take time off? Submit your leave request here.',
        'apply_for_leave': 'Apply for Leave',
        'present': 'Present',
        'absent': 'Absent',
        'sundays': 'Sundays',
        'check_in': 'Check-In',
        'check_out': 'Check-Out',
        'in_location': 'In: ',
        'out_location': 'Out: ',
        'location_not_recorded': 'Location not recorded',
        'no_attendance_history': 'No attendance history found.',
        'leave_type': 'Leave Type',
        'date_range': 'Date Range',
        'no_leave_requests_found': 'No leave requests found.',
        'my_department': 'My Department',
        'team_members': 'Team Members',
        'team_present': 'Team Present',
        'pending_approvals': 'Pending Approvals',
        'my_attendance': 'My Attendance',
        'pending_leave_requests': 'Pending Leave Requests',
        'department_employees_status': 'Department Employees Status',
        'add_employee': 'Add Employee',
        'no_pending_leave_requests': 'No pending leave requests.',
        'last_activity': 'Last Activity',
        'total_employees': 'Total Employees',
        'present_today': 'Present Today',
        'absent_today': 'Absent Today',
        'on_leave_today': 'On Leave Today',
        'employees': 'Employees',
        'departments': 'Departments',
        'leave_requests': 'Leave Requests',
        'attendance_log': 'Attendance Log',
        'analytics': 'Analytics',
        'ai_summary': 'AI Summary',
        'app_settings': 'App Settings',
        'all_employees': 'All Employees',
        'all_statuses': 'All Statuses',
        'active': 'Active',
        'inactive': 'Inactive',
        'all_roles': 'All Roles',
        'add_department': 'Add Department',
        'full_attendance_log': 'Full Attendance Log',
        'generate': 'Generate',
        'generate_summary_prompt': "Click \"Generate\" to get an AI-powered summary of today's attendance.",
        'deactivate_employee': 'Deactivate Employee',
        'deactivate_employee_confirm': "Are you sure you want to deactivate employee {username}? This action will set their status to 'inactive'.",
        'department': 'Department',
        'role': 'Role',
        'live_location': 'Live Location',
        'employee_code_short': 'Code: ',
        'reset_password': 'Reset Password',
        'deactivate': 'Deactivate',
        'department_name': 'Department Name',
        'no_pending_requests': 'No pending requests.',
        'selfie_check_in': 'Selfie Check-In',
        'selfie_check_out': 'Selfie Check-Out',
        'location_captured': 'Location captured (Accuracy: {accuracy}m)',
        'getting_location': 'Getting location...',
        'capture': 'Capture',
        'retake': 'Retake',
        'confirm_check_in': 'Confirm Check-In',
        'confirm_check_out': 'Confirm Check-Out',
        'confirm_action': 'Confirm Action',
        'are_you_sure': 'Are you sure?',
        'confirm': 'Confirm',
        'edit_department': 'Edit Department',
        'add_new_department': 'Add New Department',
        'description': 'Description',
        'no_manager': '-- No Manager --',
        'save_department': 'Save Department',
        'edit_employee': 'Edit Employee',
        'add_new_employee': 'Add New Employee',
        'profile_photo': 'Profile Photo',
        'change': 'Change',
        'full_name': 'Full Name',
        'employee_code': 'Employee Code',
        'initial_password': 'Initial Password',
        'change_password': 'Change Password',
        'password_placeholder': 'Leave blank to keep current',
        'position': 'Position',
        'save_employee': 'Save Employee',
        'sick_leave': 'Sick Leave',
        'annual_leave': 'Annual Leave',
        'unpaid_leave': 'Unpaid Leave',
        'from_date': 'From Date',
        'to_date': 'To Date',
        'error_all_fields_required': 'All fields are required.',
        'error_from_date_after_to_date': '"From Date" cannot be after "To Date".',
        'error_submit_failed': 'Failed to submit request.',
        'submit_request': 'Submit Request',
        'reset_password_for': 'Reset Password for {fullName}',
        'reset_password_prompt': 'You are resetting the password for {username}.',
        'new_password': 'New Password',
        'hide_password': 'Hide password',
        'show_password': 'Show password',
        'application_settings': 'Application Settings',
        'application_name': 'Application Name',
        'application_logo': 'Application Logo',
        'remove': 'Remove',
        'save_settings': 'Save Settings',
        'weekly_attendance_trend': 'Weekly Attendance Trend',
        'leave_requests_by_type': 'Leave Requests by Type',
        'leave_requests_by_status': 'Leave Requests by Status',
        'approved': 'Approved',
        'rejected': 'Rejected',
        'pending': 'Pending'
    },
    es: {
        'app_title': 'Sistema de Asistencia',
        'sign_in_continue': 'Por favor, inicie sesión para continuar',
        'username': 'Nombre de usuario',
        'password': 'Contraseña',
        'sign_in': 'Iniciar Sesión',
        'signing_in': 'Iniciando Sesión...',
        'quick_login_as': 'Inicio Rápido Como:',
        'employee': 'Empleado',
        'manager': 'Gerente',
        'admin': 'Administrador',
        'logout': 'Cerrar Sesión',
        'role_employee': 'Empleado',
        'role_manager': 'Gerente',
        'role_admin': 'Administrador',
        'remember_me': 'Recuérdame',
        'syncing': 'Sincronizando...',
        'synced_at': 'Sincronizado a las {time}',
        'sync_error': 'Error de Sincronización',
        'date': 'Fecha',
        'status': 'Estado',
        'reason': 'Razón',
        'actions': 'Acciones',
        'edit': 'Editar',
        'cancel': 'Cancelar',
        'approve': 'Aprobar',
        'reject': 'Rechazar',
        'name': 'Nombre',
        'location': 'Ubicación',
        'attendance_action': 'Acción de Asistencia',
        'todays_status': 'Estado de Hoy',
        'leave_management': 'Gestión de Ausencias',
        'monthly_attendance_summary': 'Resumen Mensual de Asistencia',
        'attendance_history': 'Historial de Asistencia',
        'leave_request_history': 'Historial de Solicitudes de Ausencia',
        'checked_in': 'Entrada Registrada',
        'checked_out': 'Salida Registrada',
        'not_checked_in': 'Entrada no Registrada',
        'check_in_time': 'Hora de Entrada',
        'check_out_time': 'Hora de Salida',
        'check_in_with_selfie': 'Registrar Entrada con Selfie',
        'check_out_with_selfie': 'Registrar Salida con Selfie',
        'attendance_complete_today': 'Su asistencia de hoy está completa.',
        'leave_request_prompt': '¿Necesita tiempo libre? Envíe su solicitud aquí.',
        'apply_for_leave': 'Solicitar Ausencia',
        'present': 'Presente',
        'absent': 'Ausente',
        'sundays': 'Domingos',
        'check_in': 'Entrada',
        'check_out': 'Salida',
        'in_location': 'En: ',
        'out_location': 'Fuera: ',
        'location_not_recorded': 'Ubicación no registrada',
        'no_attendance_history': 'No se encontró historial de asistencia.',
        'leave_type': 'Tipo de Ausencia',
        'date_range': 'Rango de Fechas',
        'no_leave_requests_found': 'No se encontraron solicitudes de ausencia.',
        'my_department': 'Mi Departamento',
        'team_members': 'Miembros del Equipo',
        'team_present': 'Equipo Presente',
        'pending_approvals': 'Aprobaciones Pendientes',
        'my_attendance': 'Mi Asistencia',
        'pending_leave_requests': 'Solicitudes de Ausencia Pendientes',
        'department_employees_status': 'Estado de Empleados del Departamento',
        'add_employee': 'Añadir Empleado',
        'no_pending_leave_requests': 'No hay solicitudes de ausencia pendientes.',
        'last_activity': 'Última Actividad',
        'total_employees': 'Total de Empleados',
        'present_today': 'Presentes Hoy',
        'absent_today': 'Ausentes Hoy',
        'on_leave_today': 'De Permiso Hoy',
        'employees': 'Empleados',
        'departments': 'Departamentos',
        'leave_requests': 'Solicitudes de Ausencia',
        'attendance_log': 'Registro de Asistencia',
        'analytics': 'Analíticas',
        'ai_summary': 'Resumen de IA',
        'app_settings': 'Configuración de la App',
        'all_employees': 'Todos los Empleados',
        'all_statuses': 'Todos los Estados',
        'active': 'Activo',
        'inactive': 'Inactivo',
        'all_roles': 'Todos los Roles',
        'add_department': 'Añadir Departamento',
        'full_attendance_log': 'Registro Completo de Asistencia',
        'generate': 'Generar',
        'generate_summary_prompt': 'Haga clic en "Generar" para obtener un resumen de la asistencia de hoy con IA.',
        'deactivate_employee': 'Desactivar Empleado',
        'deactivate_employee_confirm': '¿Seguro que quiere desactivar al empleado {username}? Su estado cambiará a "inactivo".',
        'department': 'Departamento',
        'role': 'Rol',
        'live_location': 'Ubicación en Vivo',
        'employee_code_short': 'Código: ',
        'reset_password': 'Restablecer Contraseña',
        'deactivate': 'Desactivar',
        'department_name': 'Nombre del Departamento',
        'no_pending_requests': 'No hay solicitudes pendientes.',
        'selfie_check_in': 'Entrada con Selfie',
        'selfie_check_out': 'Salida con Selfie',
        'location_captured': 'Ubicación capturada (Precisión: {accuracy}m)',
        'getting_location': 'Obteniendo ubicación...',
        'capture': 'Capturar',
        'retake': 'Tomar de Nuevo',
        'confirm_check_in': 'Confirmar Entrada',
        'confirm_check_out': 'Confirmar Salida',
        'confirm_action': 'Confirmar Acción',
        'are_you_sure': '¿Está seguro?',
        'confirm': 'Confirmar',
        'edit_department': 'Editar Departamento',
        'add_new_department': 'Añadir Nuevo Departamento',
        'description': 'Descripción',
        'no_manager': '-- Sin Gerente --',
        'save_department': 'Guardar Departamento',
        'edit_employee': 'Editar Empleado',
        'add_new_employee': 'Añadir Nuevo Empleado',
        'profile_photo': 'Foto de Perfil',
        'change': 'Cambiar',
        'full_name': 'Nombre Completo',
        'employee_code': 'Código de Empleado',
        'initial_password': 'Contraseña Inicial',
        'change_password': 'Cambiar Contraseña',
        'password_placeholder': 'Dejar en blanco para mantener actual',
        'position': 'Puesto',
        'save_employee': 'Guardar Empleado',
        'sick_leave': 'Ausencia por Enfermedad',
        'annual_leave': 'Vacaciones Anuales',
        'unpaid_leave': 'Ausencia no Remunerada',
        'from_date': 'Desde',
        'to_date': 'Hasta',
        'error_all_fields_required': 'Todos los campos son obligatorios.',
        'error_from_date_after_to_date': 'La "Fecha Desde" no puede ser posterior a la "Fecha Hasta".',
        'error_submit_failed': 'Error al enviar la solicitud.',
        'submit_request': 'Enviar Solicitud',
        'reset_password_for': 'Restablecer Contraseña para {fullName}',
        'reset_password_prompt': 'Está restableciendo la contraseña para {username}.',
        'new_password': 'Nueva Contraseña',
        'hide_password': 'Ocultar contraseña',
        'show_password': 'Mostrar contraseña',
        'application_settings': 'Configuración de Aplicación',
        'application_name': 'Nombre de la Aplicación',
        'application_logo': 'Logo de la Aplicación',
        'remove': 'Quitar',
        'save_settings': 'Guardar Configuración',
        'weekly_attendance_trend': 'Tendencia Semanal de Asistencia',
        'leave_requests_by_type': 'Solicitudes de Ausencia por Tipo',
        'leave_requests_by_status': 'Solicitudes de Ausencia por Estado',
        'approved': 'Aprobado',
        'rejected': 'Rechazado',
        'pending': 'Pendiente'
    },
    fr: {
        'app_title': 'Système de Présence',
        'sign_in_continue': 'Veuillez vous connecter pour continuer',
        'username': 'Nom d\'utilisateur',
        'password': 'Mot de passe',
        'sign_in': 'Se Connecter',
        'signing_in': 'Connexion en cours...',
        'quick_login_as': 'Connexion Rapide En Tant Que:',
        'employee': 'Employé',
        'manager': 'Directeur',
        'admin': 'Admin',
        'logout': 'Déconnexion',
        'role_employee': 'Employé',
        'role_manager': 'Directeur',
        'role_admin': 'Admin',
        'remember_me': 'Se souvenir de moi',
        'syncing': 'Synchronisation...',
        'synced_at': 'Synchronisé à {time}',
        'sync_error': 'Erreur de Synchronisation',
        'date': 'Date',
        'status': 'Statut',
        'reason': 'Raison',
        'actions': 'Actions',
        'edit': 'Modifier',
        'cancel': 'Annuler',
        'approve': 'Approuver',
        'reject': 'Rejeter',
        'name': 'Nom',
        'location': 'Emplacement',
        'attendance_action': 'Action de Présence',
        'todays_status': 'Statut du Jour',
        'leave_management': 'Gestion des Congés',
        'monthly_attendance_summary': 'Résumé Mensuel des Présences',
        'attendance_history': 'Historique des Présences',
        'leave_request_history': 'Historique des Demandes de Congé',
        'checked_in': 'Arrivée Enregistrée',
        'checked_out': 'Départ Enregistré',
        'not_checked_in': 'Non Enregistré',
        'check_in_time': 'Heure d\'Arrivée',
        'check_out_time': 'Heure de Départ',
        'check_in_with_selfie': 'Pointer avec Selfie',
        'check_out_with_selfie': 'Quitter avec Selfie',
        'attendance_complete_today': 'Votre présence pour aujourd\'hui est complète.',
        'leave_request_prompt': 'Besoin de prendre un congé? Soumettez votre demande ici.',
        'apply_for_leave': 'Demander un Congé',
        'present': 'Présent',
        'absent': 'Absent',
        'sundays': 'Dimanches',
        'check_in': 'Arrivée',
        'check_out': 'Départ',
        'in_location': 'Dans: ',
        'out_location': 'Hors: ',
        'location_not_recorded': 'Emplacement non enregistré',
        'no_attendance_history': 'Aucun historique de présence trouvé.',
        'leave_type': 'Type de Congé',
        'date_range': 'Période',
        'no_leave_requests_found': 'Aucune demande de congé trouvée.',
        'my_department': 'Mon Département',
        'team_members': 'Membres de l\'Équipe',
        'team_present': 'Équipe Présente',
        'pending_approvals': 'Approbations en Attente',
        'my_attendance': 'Ma Présence',
        'pending_leave_requests': 'Demandes de Congé en Attente',
        'department_employees_status': 'Statut des Employés du Département',
        'add_employee': 'Ajouter un Employé',
        'no_pending_leave_requests': 'Aucune demande de congé en attente.',
        'last_activity': 'Dernière Activité',
        'total_employees': 'Total des Employés',
        'present_today': 'Présents Aujourd\'hui',
        'absent_today': 'Absents Aujourd\'hui',
        'on_leave_today': 'En Congé Aujourd\'hui',
        'employees': 'Employés',
        'departments': 'Départements',
        'leave_requests': 'Demandes de Congé',
        'attendance_log': 'Journal des Présences',
        'analytics': 'Analyses',
        'ai_summary': 'Résumé IA',
        'app_settings': 'Paramètres de l\'App',
        'all_employees': 'Tous les Employés',
        'all_statuses': 'Tous les Statuts',
        'active': 'Actif',
        'inactive': 'Inactif',
        'all_roles': 'Tous les Rôles',
        'add_department': 'Ajouter un Département',
        'full_attendance_log': 'Journal Complet des Présences',
        'generate': 'Générer',
        'generate_summary_prompt': 'Cliquez sur "Générer" pour obtenir un résumé par IA de la présence d\'aujourd\'hui.',
        'deactivate_employee': 'Désactiver l\'Employé',
        'deactivate_employee_confirm': 'Êtes-vous sûr de vouloir désactiver l\'employé {username}? Son statut passera à "inactif".',
        'department': 'Département',
        'role': 'Rôle',
        'live_location': 'Position en Direct',
        'employee_code_short': 'Code: ',
        'reset_password': 'Réinitialiser le Mot de passe',
        'deactivate': 'Désactiver',
        'department_name': 'Nom du Département',
        'no_pending_requests': 'Aucune demande en attente.',
        'selfie_check_in': 'Arrivée par Selfie',
        'selfie_check_out': 'Départ par Selfie',
        'location_captured': 'Position capturée (Précision: {accuracy}m)',
        'getting_location': 'Obtention de la position...',
        'capture': 'Capturer',
        'retake': 'Reprendre',
        'confirm_check_in': 'Confirmer l\'Arrivée',
        'confirm_check_out': 'Confirmer le Départ',
        'confirm_action': 'Confirmer l\'Action',
        'are_you_sure': 'Êtes-vous sûr?',
        'confirm': 'Confirmer',
        'edit_department': 'Modifier le Département',
        'add_new_department': 'Ajouter un Nouveau Département',
        'description': 'Description',
        'no_manager': '-- Pas de Directeur --',
        'save_department': 'Enregistrer le Département',
        'edit_employee': 'Modifier l\'Employé',
        'add_new_employee': 'Ajouter un Nouvel Employé',
        'profile_photo': 'Photo de Profil',
        'change': 'Changer',
        'full_name': 'Nom Complet',
        'employee_code': 'Code Employé',
        'initial_password': 'Mot de passe Initial',
        'change_password': 'Changer le Mot de passe',
        'password_placeholder': 'Laisser vide pour conserver l\'actuel',
        'position': 'Poste',
        'save_employee': 'Enregistrer l\'Employé',
        'sick_leave': 'Congé Maladie',
        'annual_leave': 'Congé Annuel',
        'unpaid_leave': 'Congé sans Solde',
        'from_date': 'Du',
        'to_date': 'Au',
        'error_all_fields_required': 'Tous les champs sont obligatoires.',
        'error_from_date_after_to_date': 'La "Date de début" ne peut pas être après la "Date de fin".',
        'error_submit_failed': 'Échec de la soumission de la demande.',
        'submit_request': 'Soumettre la Demande',
        'reset_password_for': 'Réinitialiser le mot de passe pour {fullName}',
        'reset_password_prompt': 'Vous réinitialisez le mot de passe pour {username}.',
        'new_password': 'Nouveau Mot de passe',
        'hide_password': 'Masquer le mot de passe',
        'show_password': 'Afficher le mot de passe',
        'application_settings': 'Paramètres de l\'Application',
        'application_name': 'Nom de l\'Application',
        'application_logo': 'Logo de l\'Application',
        'remove': 'Supprimer',
        'save_settings': 'Enregistrer les Paramètres',
        'weekly_attendance_trend': 'Tendance Hebdomadaire des Présences',
        'leave_requests_by_type': 'Demandes de Congé par Type',
        'leave_requests_by_status': 'Demandes de Congé par Statut',
        'approved': 'Approuvé',
        'rejected': 'Rejeté',
        'pending': 'En attente'
    },
    zh: {
        'app_title': '考勤系统',
        'sign_in_continue': '请登录以继续',
        'username': '用户名',
        'password': '密码',
        'sign_in': '登录',
        'signing_in': '登录中...',
        'quick_login_as': '快速登录为:',
        'employee': '员工',
        'manager': '经理',
        'admin': '管理员',
        'logout': '登出',
        'role_employee': '员工',
        'role_manager': '经理',
        'role_admin': '管理员',
        'remember_me': '记住我',
        'syncing': '同步中...',
        'synced_at': '同步于 {time}',
        'sync_error': '同步错误',
        'date': '日期',
        'status': '状态',
        'reason': '原因',
        'actions': '操作',
        'edit': '编辑',
        'cancel': '取消',
        'approve': '批准',
        'reject': '拒绝',
        'name': '姓名',
        'location': '位置',
        'attendance_action': '考勤操作',
        'todays_status': '今日状态',
        'leave_management': '请假管理',
        'monthly_attendance_summary': '月度考勤摘要',
        'attendance_history': '考勤历史',
        'leave_request_history': '请假申请历史',
        'checked_in': '已签到',
        'checked_out': '已签退',
        'not_checked_in': '未签到',
        'check_in_time': '签到时间',
        'check_out_time': '签退时间',
        'check_in_with_selfie': '自拍签到',
        'check_out_with_selfie': '自拍签退',
        'attendance_complete_today': '您今天的考勤已完成。',
        'leave_request_prompt': '需要请假？在此提交您的请假申请。',
        'apply_for_leave': '申请请假',
        'present': '出勤',
        'absent': '缺勤',
        'sundays': '周日',
        'check_in': '签到',
        'check_out': '签退',
        'in_location': '入: ',
        'out_location': '出: ',
        'location_not_recorded': '未记录位置',
        'no_attendance_history': '未找到考勤历史记录。',
        'leave_type': '假期类型',
        'date_range': '日期范围',
        'no_leave_requests_found': '未找到请假申请。',
        'my_department': '我的部门',
        'team_members': '团队成员',
        'team_present': '团队出勤',
        'pending_approvals': '待审批',
        'my_attendance': '我的考勤',
        'pending_leave_requests': '待处理的请假申请',
        'department_employees_status': '部门员工状态',
        'add_employee': '添加员工',
        'no_pending_leave_requests': '没有待处理的请假申请。',
        'last_activity': '最后活动',
        'total_employees': '总员工数',
        'present_today': '今日出勤',
        'absent_today': '今日缺勤',
        'on_leave_today': '今日请假',
        'employees': '员工',
        'departments': '部门',
        'leave_requests': '请假申请',
        'attendance_log': '考勤日志',
        'analytics': '分析',
        'ai_summary': 'AI摘要',
        'app_settings': '应用设置',
        'all_employees': '所有员工',
        'all_statuses': '所有状态',
        'active': '在职',
        'inactive': '离职',
        'all_roles': '所有角色',
        'add_department': '添加部门',
        'full_attendance_log': '完整考勤日志',
        'generate': '生成',
        'generate_summary_prompt': '点击“生成”以获取今日考勤的AI摘要。',
        'deactivate_employee': '停用员工',
        'deactivate_employee_confirm': '您确定要停用员工 {username} 吗？此操作会将其状态设置为“离职”。',
        'department': '部门',
        'role': '角色',
        'live_location': '实时位置',
        'employee_code_short': '工号: ',
        'reset_password': '重置密码',
        'deactivate': '停用',
        'department_name': '部门名称',
        'no_pending_requests': '没有待处理的请求。',
        'selfie_check_in': '自拍签到',
        'selfie_check_out': '自拍签退',
        'location_captured': '已捕获位置（精度：{accuracy}米）',
        'getting_location': '正在获取位置...',
        'capture': '拍照',
        'retake': '重拍',
        'confirm_check_in': '确认签到',
        'confirm_check_out': '确认签退',
        'confirm_action': '确认操作',
        'are_you_sure': '您确定吗？',
        'confirm': '确认',
        'edit_department': '编辑部门',
        'add_new_department': '添加新部门',
        'description': '描述',
        'no_manager': '-- 无经理 --',
        'save_department': '保存部门',
        'edit_employee': '编辑员工',
        'add_new_employee': '添加新员工',
        'profile_photo': '头像',
        'change': '更改',
        'full_name': '全名',
        'employee_code': '员工编号',
        'initial_password': '初始密码',
        'change_password': '更改密码',
        'password_placeholder': '留空以保持当前密码',
        'position': '职位',
        'save_employee': '保存员工',
        'sick_leave': '病假',
        'annual_leave': '年假',
        'unpaid_leave': '无薪假',
        'from_date': '开始日期',
        'to_date': '结束日期',
        'error_all_fields_required': '所有字段均为必填项。',
        'error_from_date_after_to_date': '“开始日期”不能晚于“结束日期”。',
        'error_submit_failed': '提交请求失败。',
        'submit_request': '提交申请',
        'reset_password_for': '为 {fullName} 重置密码',
        'reset_password_prompt': '您正在为 {username} 重置密码。',
        'new_password': '新密码',
        'hide_password': '隐藏密码',
        'show_password': '显示密码',
        'application_settings': '应用设置',
        'application_name': '应用名称',
        'application_logo': '应用标志',
        'remove': '移除',
        'save_settings': '保存设置',
        'weekly_attendance_trend': '每周考勤趋势',
        'leave_requests_by_type': '按类型统计的请假申请',
        'leave_requests_by_status': '按状态统计的请假申请',
        'approved': '已批准',
        'rejected': '已拒绝',
        'pending': '待处理'
    },
    ur: {
        'app_title': 'حاضری کا نظام',
        'sign_in_continue': 'براہ کرم جاری رکھنے کے لیے سائن ان کریں۔',
        'username': 'صارف کا نام',
        'password': 'پاس ورڈ',
        'sign_in': 'سائن ان کریں',
        'signing_in': 'سائن ان ہو رہا ہے۔..',
        'quick_login_as': 'فوری لاگ ان بطور:',
        'employee': 'ملازم',
        'manager': 'مینیجر',
        'admin': 'ایڈمن',
        'logout': 'لاگ آؤٹ',
        'role_employee': 'ملازم',
        'role_manager': 'مینیجر',
        'role_admin': 'ایڈمن',
        'remember_me': 'مجھے یاد رکھیں',
        'syncing': 'ہم آہنگ کیا جا رہا ہے...',
        'synced_at': '{time} پر ہم آہنگ کیا گیا',
        'sync_error': 'ہم آہنگی میں خرابی',
        'date': 'تاریخ',
        'status': 'حیثیت',
        'reason': 'وجہ',
        'actions': 'کاروائیاں',
        'edit': 'ترمیم',
        'cancel': 'منسوخ',
        'approve': 'منظور',
        'reject': 'مسترد',
        'name': 'نام',
        'location': 'مقام',
        'attendance_action': 'حاضری کی کارروائی',
        'todays_status': 'آج کی حیثیت',
        'leave_management': 'رخصت کا انتظام',
        'monthly_attendance_summary': 'ماہانہ حاضری کا خلاصہ',
        'attendance_history': 'حاضری کی تاریخ',
        'leave_request_history': 'رخصت کی درخواستوں کی تاریخ',
        'checked_in': 'حاضری لگ گئی',
        'checked_out': 'واپسی ہو گئی',
        'not_checked_in': 'حاضری نہیں لگی',
        'check_in_time': 'آمد کا وقت',
        'check_out_time': 'روانگی کا وقت',
        'check_in_with_selfie': 'سیلفی کے ساتھ حاضری لگائیں',
        'check_out_with_selfie': 'سیلفی کے ساتھ روانہ ہوں',
        'attendance_complete_today': 'آج کے لیے آپ کی حاضری مکمل ہے۔',
        'leave_request_prompt': 'چھٹی کی ضرورت ہے؟ اپنی درخواست یہاں جمع کروائیں۔',
        'apply_for_leave': 'رخصت کے لیے درخواست دیں',
        'present': 'حاضر',
        'absent': 'غیر حاضر',
        'sundays': 'اتوار',
        'check_in': 'آمد',
        'check_out': 'روانگی',
        'in_location': 'اندر: ',
        'out_location': 'باہر: ',
        'location_not_recorded': 'مقام ریکارڈ نہیں کیا گیا',
        'no_attendance_history': 'حاضری کی کوئی تاریخ نہیں ملی۔',
        'leave_type': 'رخصت کی قسم',
        'date_range': 'تاریخ کی حد',
        'no_leave_requests_found': 'رخصت کی کوئی درخواست نہیں ملی۔',
        'my_department': 'میرا محکمہ',
        'team_members': 'ٹیم کے اراکین',
        'team_present': 'ٹیم حاضر',
        'pending_approvals': 'منظوری کے منتظر',
        'my_attendance': 'میری حاضری',
        'pending_leave_requests': 'زیر التواء رخصت کی درخواستیں',
        'department_employees_status': 'محکمہ کے ملازمین کی حیثیت',
        'add_employee': 'ملازم شامل کریں',
        'no_pending_leave_requests': 'کوئی زیر التواء رخصت کی درخواستیں نہیں ہیں۔',
        'last_activity': 'آخری سرگرمی',
        'total_employees': 'کل ملازمین',
        'present_today': 'آج حاضر',
        'absent_today': 'آج غیر حاضر',
        'on_leave_today': 'آج رخصت پر',
        'employees': 'ملازمین',
        'departments': 'محکمے',
        'leave_requests': 'رخصت کی درخواستیں',
        'attendance_log': 'حاضری کا لاگ',
        'analytics': 'تجزیات',
        'ai_summary': 'AI خلاصہ',
        'app_settings': 'ایپ کی ترتیبات',
        'all_employees': 'تمام ملازمین',
        'all_statuses': 'تمام حیثیتیں',
        'active': 'فعال',
        'inactive': 'غیر فعال',
        'all_roles': 'تمام کردار',
        'add_department': 'محکمہ شامل کریں',
        'full_attendance_log': 'مکمل حاضری کا لاگ',
        'generate': 'بنائیں',
        'generate_summary_prompt': 'آج کی حاضری کا AI سے چلنے والا خلاصہ حاصل کرنے کے لیے "بنائیں" پر کلک کریں۔',
        'deactivate_employee': 'ملازم کو غیر فعال کریں',
        'deactivate_employee_confirm': 'کیا آپ واقعی ملازم {username} کو غیر فعال کرنا چاہتے ہیں؟ یہ عمل ان کی حیثیت کو \'غیر فعال\' کر دے گا۔',
        'department': 'محکمہ',
        'role': 'کردار',
        'live_location': 'براہ راست مقام',
        'employee_code_short': 'کوڈ: ',
        'reset_password': 'پاس ورڈ ری سیٹ کریں',
        'deactivate': 'غیر فعال کریں',
        'department_name': 'محکمے کا نام',
        'no_pending_requests': 'کوئی زیر التواء درخواستیں نہیں ہیں۔',
        'selfie_check_in': 'سیلفی سے حاضری',
        'selfie_check_out': 'سیلفی سے روانگی',
        'location_captured': 'مقام حاصل کر لیا گیا (درستگی: {accuracy} میٹر)',
        'getting_location': 'مقام حاصل کیا جا رہا ہے...',
        'capture': 'تصویر لیں',
        'retake': 'دوبارہ لیں',
        'confirm_check_in': 'آمد کی تصدیق کریں',
        'confirm_check_out': 'روانگی کی تصدیق کریں',
        'confirm_action': 'کارروائی کی تصدیق کریں',
        'are_you_sure': 'کیا آپ کو یقین ہے؟',
        'confirm': 'تصدیق کریں',
        'edit_department': 'محکمے میں ترمیم کریں',
        'add_new_department': 'نیا محکمہ شامل کریں',
        'description': 'تفصیل',
        'no_manager': '-- کوئی مینیجر نہیں --',
        'save_department': 'محکمہ محفوظ کریں',
        'edit_employee': 'ملازم میں ترمیم کریں',
        'add_new_employee': 'نیا ملازم شامل کریں',
        'profile_photo': 'پروفائل تصویر',
        'change': 'تبدیل کریں',
        'full_name': 'پورا نام',
        'employee_code': 'ملازم کوڈ',
        'initial_password': 'ابتدائی پاس ورڈ',
        'change_password': 'پاس ورڈ تبدیل کریں',
        'password_placeholder': 'موجودہ رکھنے کے لئے خالی چھوڑ دیں',
        'position': 'عہدہ',
        'save_employee': 'ملازم کو محفوظ کریں',
        'sick_leave': 'بیماری کی رخصت',
        'annual_leave': 'سالانہ رخصت',
        'unpaid_leave': 'بلا معاوضہ رخصت',
        'from_date': 'اس تاریخ سے',
        'to_date': 'اس تاریخ تک',
        'error_all_fields_required': 'تمام خانے ضروری ہیں۔',
        'error_from_date_after_to_date': '"شروع کی تاریخ" "اختتام کی تاریخ" کے بعد نہیں ہو سکتی۔',
        'error_submit_failed': 'درخواست جمع کرانے میں ناکامی۔',
        'submit_request': 'درخواست جمع کروائیں',
        'reset_password_for': '{fullName} کے لئے پاس ورڈ ری سیٹ کریں',
        'reset_password_prompt': 'آپ {username} کے لئے پاس ورڈ ری سیٹ کر رہے ہیں۔',
        'new_password': 'نیا پاس ورڈ',
        'hide_password': 'پاس ورڈ چھپائیں',
        'show_password': 'پاس ورڈ دکھائیں',
        'application_settings': 'ایپلیکیشن کی ترتیبات',
        'application_name': 'ایپلیکیشن کا نام',
        'application_logo': 'ایپلیکیشن کا لوگو',
        'remove': 'ہٹائیں',
        'save_settings': 'ترتیبات محفوظ کریں',
        'weekly_attendance_trend': 'ہفتہ وار حاضری کا رجحان',
        'leave_requests_by_type': 'قسم کے لحاظ سے رخصت کی درخواستیں',
        'leave_requests_by_status': 'حیثیت کے لحاظ سے رخصت کی درخواستیں',
        'approved': 'منظور شدہ',
        'rejected': 'مسترد',
        'pending': 'زیر التواء'
    },
};


interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        // Get language from localStorage or default to 'en'
        return (localStorage.getItem('language') as Language) || 'en';
    });

    useEffect(() => {
        // Handle Right-to-Left (RTL) for Urdu
        if (language === 'ur') {
            document.documentElement.dir = 'rtl';
        } else {
            document.documentElement.dir = 'ltr';
        }
    }, [language]);

    const setLanguage = (lang: Language) => {
        localStorage.setItem('language', lang);
        setLanguageState(lang);
    };

    const t = useCallback((key: string, replacements?: Record<string, string | number>): string => {
        let translation = translations[language]?.[key] || key;
        if (replacements) {
            Object.keys(replacements).forEach(placeholder => {
                translation = translation.replace(`{${placeholder}}`, String(replacements[placeholder]));
            });
        }
        return translation;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
